parameters:
- name: arch
  type: string
- name: pool
  type: object
  default: {}
- name: artifact_name
  type: string
- name: codeCoverage
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: 60

  pool: ${{ parameters.pool }}

  container:
    image: sonicdev-microsoft.azurecr.io:443/sonic-slave-trixie:$(BUILD_BRANCH)-${{ parameters.arch }}

  steps:
  - ${{ if and(eq(parameters.arch, 'amd64'), parameters.codeCoverage) }}:
    - script: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get install -y dotnet-sdk-6.0
      displayName: install .Net
  - script: |
      sudo apt-get update
      sudo apt-get install -y \
          libboost-all-dev \
          libexplain-dev \
          libhiredis-dev \
          libnl-3-dev \
          libnl-route-3-dev \
          libnl-genl-3-dev \
          libnl-nf-3-dev \
          libevent-dev \
          libjsoncpp-dev \
          libpcap-dev
    displayName: "Install dependencies"
  - checkout: self
    clean: true
    submodules: true
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: Azure.sonic-buildimage.common_libs
      runVersion: 'specific'
      pipelineId: '926659'
      path: $(Build.ArtifactStagingDirectory)/download
      ${{ if eq(parameters.arch, 'amd64') }}:
        artifact: common-lib
      ${{ else }}:
        artifact: common-lib.${{ parameters.arch }}
      patterns: |
        target/debs/trixie/libyang3_*.deb
        target/debs/trixie/libyang-dev_3*.deb
        target/debs/trixie/python3-libyang_*.deb
        target/debs/trixie/libpcre*.deb
    displayName: "Download libyang from common lib"
  - script: |
      set -ex
      sudo dpkg -i $(find ./download -name *.deb)
    workingDirectory: $(Build.ArtifactStagingDirectory)
    displayName: "Install libyang from common lib"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: Azure.sonic-swss-common
      ${{ if eq(parameters.arch, 'amd64') }}:
        artifact: sonic-swss-common-trixie
      ${{ else }}:
        artifact: sonic-swss-common-trixie.${{ parameters.arch }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/$(BUILD_BRANCH)'
      displayName: "Download sonic-swss-common"
  - script: |
      set -ex
      sudo dpkg -i libswsscommon_1.0.0_${{ parameters.arch }}.deb
      sudo dpkg -i libswsscommon-dev_1.0.0_${{ parameters.arch }}.deb
    workingDirectory: $(Pipeline.Workspace)/
    displayName: 'Install libswsscommon package'
  - script: |
      rm ../*.deb
      dpkg-buildpackage -us -uc -b -j$(nproc)
      cp ../*.deb $(Build.ArtifactStagingDirectory)
    displayName: "Compile sonic dhcpmon"
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive dhcpmon debian packages"
  - ${{ if and(eq(parameters.arch, 'amd64'), parameters.codeCoverage) }}:
    - task: PublishCodeCoverageResults@1
      inputs:
        summaryFileLocation: dhcpmon-test-result.xml
        pathToSources: $(Build.SourcesDirectory)
        codeCoverageTool: 'Cobertura'
